<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
	  <Title>FactoryFoundation</Title>
	  <Authors>Michael Bradvica</Authors>
	  <Company>Simplex Software LLC</Company>
    <Description>A micro library for simple factories.</Description>
    <Copyright>Copyright (c) Simplex Software LLC 2026. All rights reserved.</Copyright>
	  <PackageProjectUrl>https://github.com/mjbradvica/FactoryFoundation</PackageProjectUrl>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <RepositoryUrl>https://github.com/mjbradvica/FactoryFoundation</RepositoryUrl>
	  <PackageTags>factory, factories, design-patterns</PackageTags>
	  <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>logo.png</PackageIcon>
	  <Version>0.9.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\images\logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
  </ItemGroup>

</Project>
